server:
   port: 6501
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/ 
   instance:
      appName:OrderService
spring:
   application:
      name: OrderService
   datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
   jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   h2:
    console.enabled: true